import 'package:blog_app/screens/widgets/widets%20and%20functions.dart';
import 'package:flutter/material.dart';

class AboutUs extends StatelessWidget {
  const AboutUs({super.key});

  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      backgroundColor: Colors.black,
      body: SingleChildScrollView(
        child: SafeArea(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TitleText(words: 'Privacy Policy'),
              DescriptionText(
                  words:
                      'Sreeraj CR built the Blogs Corner app as a Free app. This SERVICE is provided by Sreeraj CR at no cost and is intended for use as is.This page is used to inform visitors regarding my policies with the collection, use, and disclosure of Personal Information if anyone decided to use my Service.If you choose to use my Service, then you agree to the collection and use of information in relation to this policy. The Personal Information that I collect is used for providing and improving the Service. I will not use or share your information with anyone except as described in this Privacy Policy.The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which are accessible at Blogs Corner unless otherwise defined in this Privacy Policy.'),
              SizedBox(
                height: 20,
              ),
              TitleText(words: 'Information Collection and Use'),
              DescriptionText(
                  words:
                      'For a better experience, while using our Service, I may require you to provide us with certain personally identifiable information, including but not limited to image,name,username,password. The information that I request will be retained on your device and is not collected by me in any way.'),
              SizedBox(
                height: 20,
              ),
              TitleText(words: 'Log Data'),
              DescriptionText(
                  words:
                      'I want to inform you that whenever you use my Service, in a case of an error in the app I collect data and information (through third-party products) on your phone called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address, device name, operating system version, the configuration of the app when utilizing my Service, the time and date of your use of the Service, and other statistics.'),
              SizedBox(
                height: 20,
              ),
              TitleText(words: 'Cookies'),
              DescriptionText(words: "Cookies are files with a small amount of data that are commonly used as anonymous unique identifiers. These are sent to your browser from the websites that you visit and are stored on your device's internal memory.This Service does not use these “cookies” explicitly. However, the app may use third-party code and libraries that use “cookies” to collect information and improve their services. You have the option to either accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to refuse our cookies, you may not be able to use some portions of this Service."),
              SizedBox(
                height: 20,
              ),
              TitleText(words: "Children’s Privacy"),
              DescriptionText(words: "I do not knowingly collect personally identifiable information from children. I encourage all children to never submit any personally identifiable information through the Application and/or Services. I encourage parents and legal guardians to monitor their children's Internet usage and to help enforce this Policy by instructing their children never to provide personally identifiable information through the Application and/or Services without their permission. If you have reason to believe that a child has provided personally identifiable information to us through the Application and/or Services, please contact us. You must also be at least 16 years of age to consent to the processing of your personally identifiable information in your country (in some countries we may allow your parent or guardian to do so on your behalf)."),
               SizedBox(
                height: 20,
              ),
              TitleText(words: "Contact Us"),
               DescriptionText(words: "If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at sreerajcr333@gmail.com.This privacy policy page was created at privacypolicytemplate.net and modified/generated by App Privacy Policy Generator")
            ],
          ),
        ),
      ),
    );
  }
}
